### PR TITLE
Add release API feature.

### LINKED ISSUE #1925: Uploading release asset file with api
I think it will be fine to add an api to upload files to a repository. This will enable the upload of job artifacts from builds and other integrations . Github actually supports all create update delete (crud) . I am thinking this should try and fix #1892

### PR DESCRIPTION
**Pull request by kounoike**
This PR adds release API. It can close #1925 and #2231.

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
@kounoike Could you add tests to make sure JSON serialization as follows?
- https://github.com/gitbucket/gitbucket/blob/master/src/test/scala/gitbucket/core/api/ApiSpecModels.scala
- https://github.com/gitbucket/gitbucket/blob/master/src/test/scala/gitbucket/core/api/JsonFormatSpec.scala

**Comment by kounoike** [comment]
@takezoe OK, I will add such tests.

**Comment by kounoike** [comment]
@takezoe I wrote tests. Could you review this PR?

**Comment by takezoe** [comment]
@kounoike Thanks. Could you update Wiki page as well?
https://github.com/gitbucket/gitbucket/wiki/API-WebHook

**Pull request merged**
