### PR TITLE
Show userName as link only when a user is not removed

### PR DESCRIPTION
**Pull request by SIkebe**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### before
before

-----

### after
after

### CODE REVIEW

**Comment by aadrian** [comment]
@SIkebe IMHO if the user was removed, but there are commits and other elements referenced to it's name, **only** the admin should be still able to see them. 

The username link should be disabled for normal users, or for the admins when the users had no activity.

**Comment by SIkebe** [comment]
@aadrian Hmm, I consolidate the look & feel in user management page and issue/PR page.
Here's the image of a comment written by a removed user.
image

**Comment by SIkebe** [comment]
>The username link should be disabled for normal users

Only administrators can see user management page, so this PR would not affect normal users.

**Comment by aadrian** [comment]
> Only administrators can see user management page, 

But not the user page is linking to ! The URLs are predictable, and if someone has a link while the user existed (e.g. bookmarked), than it could still access it.

**Comment by takezoe** [comment]
> The username link should be disabled for normal users, or for the admins when the users had no activity.

At least, git history will be kept even after removal of GitBucket account. I don't think we should revise them.

Anyway, I think that is out of the scope of this pull request.

**Comment by aadrian** [comment]
@takezoe 

> At least, git history will be kept even after removal of GitBucket account. I don't think we should revise them.

Of course not. 

But if a user has been disabled (and not purged), and had activity, only the admin should be able to see the "user" page with that activity.

> I think how to treat removed accounts is out of the scope of this pull request.

OK.

**Comment by SIkebe** [comment]
As @aadrian said, more granular management of activities or a feature like GitLab's Audit Events would be useful, for sure.
https://docs.gitlab.com/ee/administration/audit_events.html

I just wanted to remove useless link in this PR.

**Comment by takezoe** [comment]
Let's consider treatment of removed accounts as a dedicated topic.

**Pull request merged**
