### PR TITLE
update dependencies and wording

### PR DESCRIPTION
**Pull request by aadrian**
### Before submitting a pull-request to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
@aadrian Could you divide this pull request to a wording fix and a dependencies update.

**Comment by aadrian** [comment]
@takezoe 

> Could you divide this pull request to a wording fix and a dependencies update.

Of course. 

The problem that I can't seem to be able to solve right now is the MySQL test here: 
 ```gitbucket.core.GitBucketCoreModuleSpec``` fails: the Wix API seems to fail to stop the MySQL daemon  :( . I tried with different library combinations and they all seem to fail :( .

**Comment by aadrian** [comment]
@takezoe 
I separated this PR in 2 parts as you requested:
https://github.com/gitbucket/gitbucket/pull/1532
and
https://github.com/gitbucket/gitbucket/pull/1533

Unfortunately the problem I mentioned https://github.com/gitbucket/gitbucket/pull/1526#issuecomment-292784334 with MySQL stopping problem still persists :( .

**Comment by takezoe** [comment]
@aadrian Thanks! I merged wording fix and will check MySQL test failure.

**Pull request closed without merging**
