### PR TITLE
GitLFS support

### PR DESCRIPTION
**Pull request by takezoe**
See a following blog article about GitLFS support in GitBucket to know about details of this pull request:
https://gitbucket.github.io/gitbucket-news/gitbucket/2017/01/03/git-lfs-support.html

### CODE REVIEW

**Comment by aadrian** [comment]
This is fantastic. Thank you!

**Comment by takezoe** [comment]
Added built-in GitLFS server implementation. gitbucket-lfs is not required any more.

**Comment by takezoe** [comment]
Stored LFS files location was changed.

- Before:  `GITBUCKET_HOME/lfs`
- After:  `GITBUCKET_HOME/repositories/<owner>/<repository>/lfs`

**Comment by nazoking** [comment]
👍

**Pull request merged**
