### PR TITLE
Fix get a reference API path

### LINKED ISSUE #2437: Implement git refs API
## Feature request: implement API
**Impacted version**: 4.33.0

I'm trying to get Jenkins with Github plugin to build my tags. Right now Jenkins does not discover any tags, and I think by scanning through plugin source (though I'm not 100% sure) that the GitHub plugin queries this part of the GitHub API, which I think is currently not implemented:

[Git Tags](https://developer.github.com/v3/git/tags/)

This is from the Github branch plugin [GitHubSCMSource](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java):

```
                request.listener().getLogger().format("%n  Getting remote tags...%n");
                // GitHub will give a 404 if the repository does not have any tags
                // we could rework the code that iterates to expect the 404, but that
                // would mean leaking the strange behaviour in every trait that consults the list
                // of tags. (And GitHub API is probably correct in throwing the GHFileNotFoundException
                // from a PagedIterable, so we don't want to fix that)
                //
                // Instead we just return a wrapped iterator that does the right thing.
                final Iterable<GHRef> iterable = repo.listRefs("tags");
```

This is the respective code I found within the Jenkins Github API plugin [GHRepository](https://github.com/github-api/github-api/blob/master/src/main/java/org/kohsuke/github/GHRepository.java):

```
    /**
     * Retrieves all refs of the given type for the current GitHub repository.
     *
     * @param refType
     *            the type of reg to search for e.g. <code>tags</code> or <code>commits</code>
     * @return paged iterable of all refs of the specified type
     * @throws IOException
     *             on failure communicating with GitHub, potentially due to an invalid ref type being requested
     */
    public PagedIterable<GHRef> listRefs(String refType) throws IOException {
        final String url = String.format("/repos/%s/%s/git/refs/%s", getOwnerName(), name, refType);
        return root.createRequest().withUrlPath(url).toIterable(GHRef[].class, item -> item.wrap(root));
    }
```

## Response format
This actually doesn't look like rocket science:

Here is request for Gitbucket tags: https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags

```
[
  {
    "ref": "refs/tags/1.0",
    "node_id": "MDM6UmVmOTM1MDc0NjoxLjA=",
    "url": "https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags/1.0",
    "object": {
      "sha": "1f164ecf2f59190afc8d7204a221c739e707df4c",
      "type": "tag",
      "url": "https://api.github.com/repos/gitbucket/gitbucket/git/tags/1f164ecf2f59190afc8d7204a221c739e707df4c"
    }
  },
  {
    "ref": "refs/tags/1.1",
    "node_id": "MDM6UmVmOTM1MDc0NjoxLjE=",
    "url": "https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags/1.1",
    "object": {
      "sha": "8aec16bf7f164e99605a26b337a79246ca374303",
      "type": "tag",
      "url": "https://api.github.com/repos/gitbucket/gitbucket/git/tags/8aec16bf7f164e99605a26b337a79246ca374303"
    }
  },
  ...
]
```

### PR DESCRIPTION
**Pull request by takezoe**
Closes #2437

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by solvingj** [comment]
You may want to revert this change, as the related change here was also reverted:
https://github.com/hub4j/github-api/pull/842/files

**Comment by SIkebe** [comment]
@solvingj Thanks! Then I'll create an PR and revert it.

**Comment by solvingj** [comment]
i'm not 100% certain, i'm still trying to figure out the truth

**Comment by SIkebe** [comment]
@solvingj Are you in a position to test the Jenkins Github Branch Source plugin if the fixed version released?

**Comment by solvingj** [comment]
i originally got involved this evening when i rebuilt my jenkins demo environment (which always gets latest versions of all plugins) and i began experiencing this error.  I just configured my demo instance to roll back to an older version of the relevant plugin and i'm no longer getting that error (now getting a new error) :( anyway, the original author of those commits is online now. will try to reconcile with him.

**Comment by solvingj** [comment]
@SIkebe I am now in a position to test.  I currently run `gitbucket` from the official `gitbucket/gitbucket:4` Docker image.  Are you able to release a new tag with this fix?

**Comment by SIkebe** [comment]
@solvingj No, not yet. But yon can donload latest gitbucket.war from GitHub Actions artifacts.
https://github.com/gitbucket/gitbucket/actions/runs/158731559

**Pull request merged**
