### PR TITLE
made maxFileSize in FileUploadController configurable

### PR DESCRIPTION
**Pull request by wy193777**
related to #1569

### CODE REVIEW

**Comment by wy193777** [comment]
I didn't see any controller test, do we plan to add some?

**Comment by takezoe** [comment]
@wy193777 Thanks for your pull request. I will merge this request for 4.14.

> I didn't see any controller test, do we plan to add some?

I would like to do it but we don't have any plan (or solution?) about testing controllers for now.

**Comment by aadrian** [comment]
>  we don't have any plan (or solution?) about testing controllers for now.

Isn't Scalatra responsible for a **solution** on how to test controllers?

**Comment by takezoe** [comment]
@aadrian I think Scalatra's test support is not enough in GitBucket. We would have to consider about some additional points.

**Pull request merged**
