### PR TITLE
Add markdown toolbar

### LINKED ISSUE #1793: Add Markdown toolbar and help

### PR DESCRIPTION
**Pull request by onukura**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### About this PR
This PR add markdown toolbar to resolve #1793 
I didn't use any markdown editor such as simpleMDE because of integration with GitBucket dropzone and parsing for preview by renderer.

pr_screenshot (0)

### CODE REVIEW

**Review by SIkebe — COMMENTED** [review]
I think it needs some design discussion (e.g. where to insert new characters, where to focus after the event occurred ...), but overall it looks nice!

>I didn't any markdown editor library because of integration with GitBucket dropzone and parsing for preview by renderer.

You wrote these new functions without transpile or polyfill, which other libraries usually do, so they do not work in some browsers (e.g. IE11, Firefox for Android). However I think you don't have to care about such cases as most users uses modern browsers on their PC and you can write markdown by hand in the same manner as before.
Even Microsoft will stop supporting IE on their web services 😄 
https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

**Comment by onukura** [comment]
@SIkebe Thank you for your review! I will fix docs for function first as you suggested!

**Comment by onukura** [comment]
@SIkebe 

> I think it needs some design discussion (e.g. where to insert new characters, where to focus after the event occurred ...), 

Actually I configured how those symbols such as `###`, `****` will be inserted in text and where to focus after event referring to GitHub. (but not completely...).  
But still I agree with you opinion that we need discuss about design, like what button we want. where, in what order, etc.
I would appreciate If you guys would have any suggestion.

**Comment by onukura** [comment]
For reference, I will put gif of each button's behavior.

## Heading `###`

pr_screenshot_head

## Bold `****` and Italic `__` and Code ``

pr_screenshot_bold_italic_code

## Quote `>` and lists `-`, `1.` and task list `- []`

pr_screenshot_quoate_list

## Link `[](url)`

pr_screenshot_link

**Comment by SIkebe** [comment]
>I configured how those symbols such as `###`, `****` will be inserted in text and where to focus after event referring to GitHub. (but not completely...).

I don't think it's necessary to copy all behaviors. 
I just want to make sure, are these intended difference?
b_i

**Comment by SIkebe** [comment]
If it's an empty textarea, extra lines are inserted.

extra-line

**Comment by onukura** [comment]
> > I configured how those symbols such as `###`, `****` will be inserted in text and where to focus after event referring to GitHub. (but not completely...).
> 
> I don't think it's necessary to copy all behaviors.
> I just want to make sure, are these intended difference?
> b_i

This one is yes. I just didn't support range selector...



> If it's an empty textarea, extra lines are inserted.
> 
> extra-line

This one is yes too. I know it works like this.

**Comment by onukura** [comment]
Fixed behavior for list insert when textarea is empty.

pr_screenshot_list

**Comment by aadrian** [comment]
IMHO it looks very good.

Another possibility is that we declare this a "feature preview": we included it in the distribution, to get more feedback from the end-users, so we might improve it later if required.

**Comment by onukura** [comment]
I will revise this PR as new PR because it got messy...

**Pull request closed without merging**
