### PR TITLE
Easily extended systems as greasemonkey / user scripts.

### PR DESCRIPTION
**Pull request by nazoking**
Administrator set site-script url, and footer of all pages has this url as script src.
Site script will work in the same way as Greasmonkey.

Administrator if you have their own repository, it can be used as a script file storage that you can easily manage the history and permissions.

### CODE REVIEW

**Comment by takezoe** [comment]
@nazoking It's a good idea to extend GitBucket easily! But test compilation is failed. Could you fix it?

**Comment by nazoking** [comment]
sorry, i fix it.

**Comment by takezoe** [comment]
@nazoking We can substitute the new plug-in system for this feature. New plug-in system comes in the next release 2.9. Check this example:
https://github.com/takezoe/gitbucket-gist-plugin/blob/1a698390ba383b23c64c6cc4c8608e2f3863a7bf/src/main/scala/Plugin.scala#L18-L21

**Comment by nazoking** [comment]
out of date

**Pull request closed without merging**
