### PR TITLE
Install plugins from the plugin registry

### LINKED ISSUE #1468: Plugin auto discovery & plugin registry
This issue is created to expose/gather needs/idea for a future implementation of a plugin discovery/installation system in gitbucket probably working together with a plugin registry.

# Requirements to provide a plugin installation mechanism in gitbucket

## with internet access

- a central registry exists
- the registry exposes API to retrieve plugin information
    + plugin name/description/version/download URL
- with hotdeployment
    + gitbucket download the new plugin/version
    + gitbucket/plugins stop/unload old plugin classes & services
    + gitbucket deploy the downloaded plugin into GITBUCKET_HOME/plugin-name.jar erasing the previously installed one (if one existed)
    + gitbucket creates an URLClassLoader for this plugin and initialize it
- without hotdeployment
    + gitbucket download the new plugin/version
    + gitbucket stores it in a temporary place
    + on next reload, before starting plugins, gitbucket deploy the plugin from temporary place into GITBUCKET_HOME/plugin-name.jar erasing the previously installed one (if one existed)
    + gitbucket creates an URLClassLoader for this plugin and initialize it

## without internet access

- gitbucket server does not see the internet, but user does
- a central registry exists
- the registry exposes page to select plugins/version to installation
- a download action is available to collect a packaging of the selected plugins
- user put the downloaded package in some location
- on startup or with hotdeployment gitbucket is capable of extracting plugins from this downloaded package

### Pure static registry

Can be a simple website exposing static data (json, xml, yaml) via for example github pages.

__PRO__: simple, fast to setup, good enough to start, running cost is 0  
__CONS__: need pure manual update, cannot gather/expose feedback from gitbucket installations

### Static registry updated automatically

Same as the pure static registry with some automation to update the data.
Could be some implemented with some build script running continuous integration systems (like travis-ci, circleci, ...) to execute some logic to update the static data
- for each registered plugin
    - fetch its latest data (via github API, ...)
    - update the static data file
   - commit/push them back

__PRO__: provide dynamic behavior, running cost is 0  
__CONS__: need a CI service offering "cron" like feature, cannot gather/expose feedback from gitbucket installations

### Dynamic registry 

The registry is a webapplication hosted somewhere.

__PRO__: cover every possible scenario including dynamic feedback from gitbucket installations (number of installations, plugin incompatibilities, starring, ...)
__CONS__: requires CPU Power + data storage

### PR DESCRIPTION
**Pull request by takezoe**
The plugin registry is working experimentally at: https://plugins.gitbucket-community.org/

Plugins are built automatically for each GitBucket and plugin version, and generates [plugins.json](https://plugins.gitbucket-community.org/releases/plugins.json). GitBucket plugin manager installs plugins by refering this file. For now, only official plugins are registered to the registry.

Closes #1468

### CODE REVIEW

**Comment by McFoggy** [comment]
Waow, I am exited to test that!

**Comment by aadrian** [comment]
@takezoe could you please also add:
 - https://github.com/gitbucket-plugins/gitbucket-explorer-plugin
 - https://github.com/gitbucket-plugins/gitbucket-announce-plugin
to the experimental registry?

**Comment by takezoe** [comment]
@aadrian Yes, I will register them next. However to register plugins to the registry, they must fill some requirements (e.g. use the latest version of sbt-gitbucket-plugin). So I have to update plugins before register them.

**Comment by takezoe** [comment]
> Good to know. Could we formulate a blog post about what else would be required for a plug-in to be compatible with the Registry?

Yes, I will create a document to describe requirements on the plugin registry website.

**Pull request merged**
