### PR TITLE
make Plugin an abstract class to improve binary compatibility

### PR DESCRIPTION
**Pull request by ritschwumm**
is this everything you wanted to do about #1090, or is there more?

### CODE REVIEW

**Comment by takezoe** [comment]
@McFoggy Changing trait breaks binary compatibility certainly in Scala. So using abstract class instead of trait is a good practice to keep binary compatibility.
There are a migration support tool named [migration-manager](https://github.com/typesafehub/migration-manager) originally provided by Typesafe. We can check binary compatibility using this tool.

**Comment by takezoe** [comment]
@ritschwumm Thanks for your work. This modification breaks binary compatibility. So I will merge this request just before next change of `Plugin`.

**Comment by McFoggy** [comment]
@takezoe the usage of clirr just reveal incompatible changes when they come. It does not mean we cannot introduce some when it is expected and fully controled. As you probably already noticed I am a java developer, so I propose the tool I know ;-) But for sure any tooling that does the same is ok to use. Having that in gitbucket tooling would help when enhancements & refactoring are introduced ; or at least it would help to communicate with external consumers (plugin providers mainly).

**Comment by takezoe** [comment]
@McFoggy This request is merged in 3.14 because I would like to add some new extension points to `Plugin`.

**Pull request merged**
