### PR TITLE
Add Cache-Control header for _avatar and /plugin-assets (refs #777)

### PR DESCRIPTION
**Pull request by kounoike**
For reduce network connection and CPU usage, add Cache-Control header.

On my PC, _avatar image transfer requires ~30ms per user.
/plugin-assets requires 200~300ms per file.
on #1489, some CSS/JS moved to /plugin-assets, it requires maybe 1s.
Because browser caches these files, it makes good effect to CPU usage too.

max-age=3600 means 60*60sec. There is no reason to chose this time.

### Before submitting a pull-request to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
This fix looks good, but it might confuse users (or plugin developers may got confused in some cases) when avatar images or plugins are updated because these resources are not available immediately. It may be also necessary a capability to add hash to the url of these resources.

**Comment by kounoike** [comment]
I think add deprecated annotation to old assets(implicit context: Context): String is better for plugin developer.
Should use new assets(path: String)(implicit context: Context): String.

In #1489, I add pluginAssets(). It should be rewrite similary.

**Comment by takezoe** [comment]
> I think add deprecated annotation to old assets(implicit context: Context): String is better for plugin developer.

@kounoike Thanks. I will add several fixes including this after merging.

**Comment by takezoe** [comment]
Fix #1491

**Comment by takezoe** [comment]
Fix #777

**Pull request merged**
