### PR TITLE
Add list-public-repositories API

### PR DESCRIPTION
**Pull request by onukura**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

## About this PR.

This PR adds list public repositories API.
https://docs.github.com/en/rest/reference/repos#list-public-repositories

but still since param is not suppoted.

### CODE REVIEW

**Review by takezoe — APPROVED** [review]
Basically, this looks good to me. However, if GitBucket has too many public repositories, this endpoint can be significantly slow. It would be nice if we can implement pagination as GitHub. It can be a future work.

**Comment by onukura** [comment]
> It would be nice if we can implement pagination as same as GitHub. It can be a future work.

I fully agree with you!

**Comment by takezoe** [comment]
@onukura Could you also update Wiki page? Adding this new endpoint to the list with (since v4.35.0) is fine.
https://github.com/gitbucket/gitbucket/wiki/API-WebHook

**Comment by onukura** [comment]
@takezoe Thank you for merging PR! I added this endpoint to the list in wiki.

**Pull request merged**
