### PR TITLE
Add HTTPS support for JettyLauncher

### PR DESCRIPTION
**Pull request by imeszaros**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
Thank you! This looks good to me.

By the way, I think it would be great if we can additionally configure the embedded jetty to redirect HTTP to HTTPS when we enable HTTPS (ref: https://stackoverflow.com/questions/26123604/redirect-from-http-to-https-automatically-in-embedded-jetty). In that case, additional configuration would be necessary like `--connectors=http,https --redirect_https=true`. What do you think about this?

**Comment by takezoe** [comment]
Note: we also have to update Wiki for CLI options: https://github.com/gitbucket/gitbucket/wiki/Basic-configurations

**Comment by takezoe** [comment]
@imeszaros  Directly updating Wiki pages is okay. We allow editing Wiki pages for everyone who has a GitHub account.

**Comment by imeszaros** [comment]
@takezoe Oh i see! That was exactly my thouht that the wiki should not be updated before the next version gets released. But with the version annotations it's ok!

**Pull request merged**
