### PR TITLE
Enable matching URLs end with slash

### PR DESCRIPTION
**Pull request by johnthemountainy**
Hi.
If we make a request to http://localhost:8080/username/, we will receive 404 status code.
This PR supports end slash in some urls.

Thank you for good product!

### CODE REVIEW

**Comment by geek1011** [comment]
Any news on this?

**Comment by nigelsim** [comment]
Any chance this can get merged soon? This is an issue for us as the Jenkins GitHub Plugin appends a slash to the URL supplied to it. Additionally, because the 404 page for GitBucket is the builtin Jetty one it is confusing to users when they hit these URLs.

**Comment by tundratim** [comment]
Any further progress on this issue?

**Comment by vidkun** [comment]
Any updates on when we can get a fix for this trailing slash issue? This is also breaking our Jenkins integration as well.

**Comment by tundratim** [comment]
Any idea on when this will go into a release?

**Comment by lefou** [comment]
It can be frustrating sometimes, when a maintainer doesn't comment.

**Comment by tundratim** [comment]
@lefou  Well ... the maintainers are pretty much all volunteering their time, so I don't think being cross with them is warranted.  I just would like an ETA for this fix even if it's 10 months out or whatever.

**Comment by takezoe** [comment]
Sorry, I couldn't mention this for a long time because I thought that supporting URL with `/` partially is not good idea. If we support it, we should support in GitBucket as a whole. And we should be carefully to accept this change because if URL specification is changed once, we can't change it easily in the future.

Anyway, supporting URL with `/` to help Jenkins integration is meaningful. I would like to advance this topic.

**Comment by McFoggy** [comment]
@takezoe not clear to me in #1840 who is adding the trailing '/'. Is it jenkins or nginx?

> And we should be carefully to accept this change because if URL specification is changed once, we can't change it easily in the future.

This is perfectly understandable but IMO http browsing on:
- `GITBUCKET/username` is probably exactly the same as `GITBUCKET/username/`
- `GITBUCKET/username/repository` is also probably the exact same as `GITBUCKET/username/repository/`

**Comment by vidkun** [comment]
@McFoggy From what I can tell, it appears to be jenkins that is adding the '/'. If it were nginx, I'd expect it to be added when trying to directly browse to a URL as well. However, we are only seeing it on the jenkins integration.

**Comment by takezoe** [comment]
I created an another pull request #1921 that makes possible to support path which ends with slash for all actions.

**Comment by takezoe** [comment]
Fixed in #1921

**Pull request closed without merging**
