### PR TITLE
Implement draft pull request related APIs

### PR DESCRIPTION
**Pull request by SIkebe**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by SIkebe** [comment]
This is the same error...it's just because windows builds in Travis CI are in early access stage?
https://travis-ci.org/gitbucket/gitbucket/jobs/596052727#L293-L294

My local windows 10 has no problems.

**Comment by SIkebe** [comment]
I restarted the build, then it succeeded this time.

**Comment by SIkebe** [comment]
@takezoe Rebased onto current master.

**Comment by takezoe** [comment]
Sorry. I had overlooked this pull request. Will be included in 4.34.0. 🙇

**Pull request merged**
