### PR TITLE
Java 8 is a new requirement

### PR DESCRIPTION
**Pull request by ritschwumm**

### CODE REVIEW

**Comment by takezoe** [comment]
Should we also update a blog post?
https://github.com/gitbucket/gitbucket-news/blob/gh-pages/_posts/2016-01-30-gitbucket-3.11.markdown

**Comment by benjixx** [comment]
@takezoe Please also update the release notes and probably blog post for version 3.11. It took me some time to figure out that Java 8 is required, as my environment is still on CentOS 6.7 with Java 7 running.

**Comment by ritschwumm** [comment]
i think it should be updated, but i don't know what to write.

**Comment by takezoe** [comment]
OK, I updated [release notes](https://github.com/gitbucket/gitbucket/releases/tag/3.11) and [blog post](https://github.com/gitbucket/gitbucket-news/commit/3e944ba88aa7957ab8ee2fbe9fb040185b9f3760).

**Pull request merged**
