### PR TITLE
add docker hint

### PR DESCRIPTION
**Pull request by pgollor**
I have been testing the container for a few months in my university and it works fine. And I will try to update the container as soon as possible if a new gitbucket version is available.

### CODE REVIEW

**Comment by aadrian** [comment]
-1

There's already described https://github.com/gitbucket/gitbucket/wiki/FAQ#3-docker-image

**Comment by pgollor** [comment]
Sorry I had forgot to check the FAQ. Sorry for that.

**Comment by pgollor** [comment]
But I think my container with mariadb and a docker compose file is a bit easier to use than the container from f99aq8ove.

**Comment by aadrian** [comment]
@pgollor I could add an extra Wiki page describing the several Docker projects exist, so the users can choose one, since there's also one form the main author of GitBucket: https://github.com/takezoe/gitbucket-docker (and many other)

Or another idea would be to improve https://github.com/takezoe/gitbucket-docker (with PRs) with serveral tags for different combinations.

**Comment by takezoe** [comment]
> I could add an extra Wiki page describing the several Docker projects exist

Sounds good!

**Comment by pgollor** [comment]
Okay thanks for your help. A didn't know that there is an docker container available from takezoe.
I think an extra wiki page is the best solution too. My english is not the best, but if you need help to describe my solution with docker compose please feel free to ask me @aadrian .

**Comment by aadrian** [comment]
@takezoe @pgollor here's an initial cut of the WIKI page https://github.com/gitbucket/gitbucket/wiki/Docker (also linked from the index/install section, and from the FAQ too)

**Comment by pgollor** [comment]
Many Thanks for that. It think this is a good overview.
@aadrian could you please add my image https://hub.docker.com/r/pgollor/gitbucket/ to the images list on that page too? This would be great.

**Comment by aadrian** [comment]
@pgollor please add more description to the official Docker page https://hub.docker.com/r/pgollor/gitbucket/ since that is used by the search engine (and not the URL you are linking to)

**Comment by pgollor** [comment]
@aadrian I added two simple sentences, because i have no time to administrate documentations on different places. If you type `gitbucket` inside the docker help you will find my container on search page 3. I hope this is enough?

**Pull request closed without merging**
