### PR TITLE
Added automatic rescaling to avatar images (Fixes #835)

### LINKED ISSUE #835: avatar need to be resized and/or cached
One of our colleagues pushed in his profile a big avatar file.

This introduced some latency, especially on the activity page, due to the fact that avatars are not cached and/or are not resized for common use cases.

It could be expected that gitbucket either:
- provides some caching information for avatar URLs. When looking at network activity in chromedev tools show always a 200 for avatar, never a 304.
- pre-computes/generates images in the expected size for avatar. On activity page, we download avatars in their full size just to resize them in 16x16

### PR DESCRIPTION
**Pull request by DrDub**
It adds a dependency on https://github.com/coobird/thumbnailator which seems the smaller dependency for this type of image processing.

### CODE REVIEW

**Comment by McFoggy** [comment]
looks good to me, can you rebase please?

**Comment by DrDub** [comment]
Great, rebased.

**Comment by nazoking** [comment]
@takezoe @McFoggy How about you to merge this? Or is there anything to worry about?

**Comment by McFoggy** [comment]
As I said, it looks ok to me but I let @takezoe to decide when to merge it.

**Comment by takezoe** [comment]
Merged. Sorry for my slow response!

**Comment by nazoking** [comment]
@takezoe thanks you!

**Pull request merged**
