### PR TITLE
Branch protectection

### PR DESCRIPTION
**Pull request by nazoking**
refs #962

 * create `Branches` setting page on repository settings page as `repo/settings/branches`
   * move `Default branch` section from `Options` to `Branches`
   * create `Protected branches` section
     * branch selector.
       * create `Branch protection` as repo/settings/branches/:branchName
       * option `Protect this branch`
       * option `Require status checks to pass before merging`
       * option `Include administrators`
         * administrators is owner of user repository or manager of group repository ( really ? )
       * option `Status checks` (multi select, from found in the last week for this repository)
     * `Edit` button on each protected branches.
 * Protected mark(octicon-shield) on repository `Branches` view page
   * disable `delete` button of protected branch.
 * check on git servlet pre-receive.
   * error if branche is procected branch and
     * push is force push
     * push is delete branch
     * push if new commit-id has not `commit-status` ok on `Status-checkes`.
 * deisable file edit on web if branch is protected and need-status-check.
   * only can create new branch...(not yet)
 * on pull-request page
    * show commit-status if context is require status checks to pass.
    * disable merge if new commit-id has not `commit-status` ok on `Status-checkes`.
    * if some status includes required is not success, merge button is disabled.
    * if any required status is success, and some status not includes required, merge button is active, but button color is white.
    * if any required status is success, merge button is active, and button color is green.
    * update branch button
      * merge `base branch` into `head branch`
      * update can only user that has `write-access` for `head branch`
 * Add API https://developer.github.com/v3/repos/#enabling-and-disabling-branch-protection
   * (currently available for developers to preview ...)

### CODE REVIEW

**Comment by takezoe** [comment]
@nazoking Thanks for your great request!

I modified your request for some reason. Mainly, added an extension point to hook pushing to git repository by plugin and updated the branch protection implemented this request to use this extension point.

I pushed my changes to `team-lab-feature/protected-branch`. Could you test this branch?

**Comment by nazoking** [comment]
@takezoe thanks you for review.

I think that parameter `receivePack: ReceivePack` is more extensible than `isAllowNonFastForwards: Boolean`.

```
def preCommit(owner: String, repository: String, receivePack: ReceivePack, command: ReceiveCommand, pusher: String)(implicit session: Session)
```

And plugin auther wil need `post-recive hook`.

And.. `recive` timing is not only push but also edit on web-ui .( edit file, merge pull-request, delete branch...)

**Comment by takezoe** [comment]
@nazoking Thanks.

> I think that parameter receivePack: ReceivePack is more extensible than isAllowNonFastForwards: Boolean.
> And plugin auther wil need post-recive hook.

You are right. Fixed.

> And.. recive timing is not only push but also edit on web-ui .( edit file, merge pull-request, delete branch...)

I think receive-hook is not same as commit-hook. Direct editing from web-ui should call commit-hook, but receive-hook should not be called. I would like to add **receive-hook** extension point with branch protection in the next GitBucket release.

**Comment by nazoking** [comment]
> I think receive-hook is not same as commit-hook. Direct editing from web-ui should call commit-hook, but receive-hook should not be called. 

right.

Your branch looks goot. thanks.

**Comment by takezoe** [comment]
@nazoking Merged. This is a big feature in GitBucket 3.11. Thanks for your great contribution!

**Comment by McFoggy** [comment]
@nazoking @takezoe just one word : Congratulations !

BIG BIG thanks to you both. This PR is a great improvement !

**Comment by rinfield** [comment]
:smile::tada:

**Comment by sthaiya** [comment]
Am getting update error on trying to protect branch.

**Comment by msigley** [comment]
I am also getting the update error.

**Comment by alwibrm** [comment]
Can anyone please explain how this feature can be used to ensure server-side hooks (like pre-commit)? Maybe @nazoking or @takezoe?

**Pull request merged**
