### PR TITLE
Enable safe optimisations in scalac

### PR DESCRIPTION
**Pull request by hrj**
As discussed in https://github.com/gitbucket/gitbucket/commit/a024491296578f00893857d3b704e9f28d7b9524

### CODE REVIEW

**Comment by hrj** [comment]
Looks like this fails on Java 9. I am not sure of where the problem lies (Java 9, Scalac, etc).

Merge or close as you please.

**Comment by xuwei-k** [comment]
Maybe `IllegalArgumentException` issue will fix in Scala 2.12.2 
- https://github.com/scala/scala-asm/commit/ccbe1cad9c27303043f43bce16dda948e3285fff
- https://github.com/scala/scala/commit/8136057e7c4a403433fd4c66b32de7df972029fe

**Comment by xuwei-k** [comment]
https://github.com/gitbucket/gitbucket/commit/c6449d4c101ef06685b56326182f4aa891ad4623

**Comment by hrj** [comment]
Thanks @xuwei-k 

I merged `origin/master` and pushed to this branch. The tests are now passing on Java 9 as well!

The tests seem to take lesser time now (6 minutes v/s 12 minutes on master). So the optimisations seem to be effective. Although I am surprised that they are so effective for this project!

**Comment by xuwei-k** [comment]
> The tests seem to take lesser time now (6 minutes v/s 12 minutes on master). So the optimisations seem to be effective. Although I am surprised that they are so effective for this project!

I don't think so. Where did you see?


enable optimizations
https://travis-ci.org/gitbucket/gitbucket/jobs/227124203#L568
> [success] Total time: 165 s, completed Apr 29, 2017 12:24:37 PM

master
https://travis-ci.org/gitbucket/gitbucket/jobs/227283350#L560
> [success] Total time: 167 s, completed Apr 30, 2017 4:35:24 AM

**Comment by takezoe** [comment]
Anyway, since error has been resolved, I merge this pull request.

**Comment by hrj** [comment]
@takezoe Thanks!

@xuwei-k I was looking at the time from Travis, but there was some confusion in my interpretation of the times. Travis shows aggregate time (12mins) on the build page while showing job time (6mins) on the individual job's page.

**Pull request merged**
