### PR TITLE
Add Get-branch-protection, Delete-branch-protection, Get-all-status-check-contexts API

### PR DESCRIPTION
**Pull request by onukura**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

## About this PR

This PR adds Web API endpoints below

- [Get branch protection](https://docs.github.com/en/rest/reference/repos#get-branch-protection)
- [Delete branch protection](https://docs.github.com/en/rest/reference/repos#delete-branch-protection)
- [Get all status check contexts](https://docs.github.com/en/rest/reference/repos#get-all-status-check-contexts)
- [Get status checks protection](https://docs.github.com/en/rest/reference/repos#get-status-checks-protection)

### CODE REVIEW

**Comment by onukura** [comment]
Ops. I should have updated test case...

**Comment by takezoe** [comment]
@onukura There is conflict with #2575. Could you resolve it?

**Comment by onukura** [comment]
@takezoe Conflict fixed!

**Comment by onukura** [comment]
I added [Get status checks protection](https://docs.github.com/en/rest/reference/repos#get-status-checks-protection) endpoint.

**Comment by takezoe** [comment]
Thanks!

**Comment by takezoe** [comment]
Hmm... This pull request seems to broke the branch protection setting form. Status checking setting is not persistent in the current master.

**Comment by takezoe** [comment]
`ApiPath` cannot be used for input case classes. In this case, `ApiBranchProtection` is used for both input and output and `ApiPath` is used in `Status` without wrapping by `Option`. Therefore, it seems to fail to deserialize JSON to `Status`. We have two options to solve the issue here:

- Use different case class for input/output instead of `ApiBranchProtection`
- Wrap `ApiPath` by `Option` and give `Some` value only for output

Also, JSON serialization/deserialization test would be necessary to avoid this kind of implicit corruption.

**Comment by takezoe** [comment]
Created a pull request: https://github.com/gitbucket/gitbucket/pull/2600

**Comment by onukura** [comment]
@takezoe Thank you for your work to fix my PR! I should have noticed before...

**Pull request merged**
