### PR TITLE
Support uploading PDF files

### PR DESCRIPTION
**Pull request by nus**
Support uploading PDF files from a issue comment form.
See also https://github.com/blog/2061-attach-files-to-comments
and #12 .

### CODE REVIEW

**Comment by takezoe** [comment]
@nus Don't you need other file type (Word, Excel and PowerPoint) support?

**Comment by imeszaros** [comment]
I think uploading more kind if popular files would be very useful..

txt, rtf, office files, etc..

**Comment by nus** [comment]
Thanks for your comments.

@takezoe I prefer PDF to other Document formats. That's the reason why I selected a PDF.

I will add below file formats.
- [x] PDF .pdf
- [ ] Word .docx, .doc
- [ ] Excel .xlsx
- [ ] Powerpoint .pptx
- [ ] Text .txt
- [ ] RTF .rtf

Does anyone want to add other file formats?

**Comment by takezoe** [comment]
@nus Please notice, GitBucket is according to GitHub specification basically. So we might reject implementation of more than over GitHub.

**Comment by nus** [comment]
The following extensions are allowed for upload.

- .gif
- .jpg
- .png
- .docx
- .pptx
- .xlsx
- .txt

**Pull request merged**
