### PR TITLE
Add plugin list API

### PR DESCRIPTION
**Pull request by kounoike**
I want this feature to use in plugin building farm.

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
API implementation looks good except that a path is not necessary to be under `/api/v3`. I think GitBucket specific APIs should be separated from GitHub compatible APIs such as `/api/gitbucket/plugins`.

> I want this feature to use in plugin building farm.

Could you tell how do you use this API  in plugin build farm?

**Comment by kounoike** [comment]
> API implementation looks good except that a path is not necessary to be under /api/v3. I think GitBucket specific APIs should be separated from GitHub compatible APIs such as /api/gitbucket/plugins.

I think it is better too. but, such implementation needs larger impacts:

- `ApiController` mounted on "/api/v3"
- `apiAuthenticationFilter` registered on "/api/v3/*"
- and other changes?

Can I change these implementations?

> Could you tell how do you use this API in plugin build farm?

I want to check each plugin successfully loaded or not. In current version, it can be checked with System administration > Plugins page. But it requires sign in (it means, form control/session control required).

If this PR is merged, I can be checked by `curl | jq` or `curl | grep`.

**Comment by kounoike** [comment]
How about `/api/v3/gitbucket/plugins`? It means "v3-compatible GitBucket specific API". So, maybe we will implement GraphQL based API (`/api/graphql`) in the future.

**Comment by takezoe** [comment]
> I think it is better too. but, such implementation needs larger impacts:

Completely understandable. `/api/v3/gitbucket/plugins` seems to make sense.

> I want to check each plugin successfully loaded or not.

OK, I understood that we will able to check whether plugins are actually loadable on specific version of GitBucket using this API.

**Comment by kounoike** [comment]
@takezoe I changed API URL.

**Pull request merged**
