### PR TITLE
Add get-commits-list-api

### PR DESCRIPTION
**Pull request by oshiro3**
This PR adds list commits api.
https://developer.github.com/v3/repos/commits/#list-commits

Only `sha` of paramater is implemented

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
@oshiro3 Thanks! Could you update https://github.com/gitbucket/gitbucket/wiki/API-WebHook, too?

**Comment by oshiro3** [comment]
@takezoe 
Thanks for accepting my PR!! 

I haven't updated it yet. If update APIs, should the PR author update the WIKI?
Is it okay for me to update this one at the current timing?

**Comment by takezoe** [comment]
I hope API authors help to update the API list, but not mandatory. It won't confuse even if we update the list before the release as long as the introduced version is mentioned like `(since x.x.x)`.

**Comment by oshiro3** [comment]
OK. I updated WIKI!

**Comment by takezoe** [comment]
Great thanks!

**Pull request merged**
