### PR TITLE
additional params to upload timeout and file size - Issue #1892

### PR DESCRIPTION
**Pull request by skullwritter**
### Before submitting a pull-request to GitBucket I have first:
This is relative to #1892
- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [x] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by skullwritter** [comment]
@takezoe see if this is what you wanted as the params

**Comment by SIkebe** [comment]
@skullwritter Could you react to a comment from @takezoe in this PR?
https://github.com/gitbucket/gitbucket/issues/1892#issuecomment-524649720

>How do you think about adding parameters for large files? Maybe, parameter names can be shortened though.
>
>- `--max_file_size_for_large_files`
>- `--upload_timeout_for_large_files`
>
>We can use these parameters for large file uploading. It might be only Releases for now, though.

Also it would be helpful if you edit the PR title more appropriate one.

**Comment by skullwritter** [comment]
@SIkebe i've already reacted to him, thats why i've addered this pull request right after
and the title is corrected

**Comment by skullwritter** [comment]
@SIkebe also, i've adhered the params as follows (in the comments from #1892 )
> @takezoe the params available on the new pull request are:
> 
> * `--max_file_size_issues=[MAX_FILE_SIZE_FOR_ISSUES]` (defaults to max_file_size)
> * `--upload_timeout_issues=[MAX_UPLOAD_TIME_IN_SECONDS_FOR_ISSUES]` (defaults to upload_timeout)
> * `--max_file_size_releases=[MAX_FILE_SIZE_FOR_RELEASES]` (defaults to max_file_size)
> * `--upload_timeout_releases=[MAX_UPLOAD_TIME_IN_SECONDS_FOR_RELEASES]` (defaults to upload_timeout)

**Comment by SIkebe** [comment]
>i've already reacted to him

Yep, partly though. He suggested other param names. 
* `--max_file_size_for_large_files`
* `--upload_timeout_for_large_files`

**Comment by skullwritter** [comment]
@SIkebe i can modify the params, the problem with that params in question is that they don't indicate where they will be applied

**Comment by skullwritter** [comment]
@SIkebe  and the params as is, that would require rewriting the dropfile jquery plugin

**Comment by skullwritter** [comment]
@SIkebe and adding other params like:
min file size to know if is a large file

**Comment by SIkebe** [comment]
>the problem with that params in question is that they don't indicate where they will be applied

I think doc can cover that. In order to understand which size is allowed exactly, users have to read the doc. Param name doesn't have to cover all information.

GitBucket has several pages that allow uploading files; e.g. Issues, Pull requests, Releases, Wiki...
In addition, there will probably be more in the future.
Having limitation for each place is not very realistic.

So two limits, one for the default and the other one for large files, would be a viable option.

**Comment by skullwritter** [comment]
hmmm..... the issues params i think it covers the pull request too, if i'm not mistaken, because i think that the issues and the pull requests uses the same form

**Comment by takezoe** [comment]
Sorry for my very late reaction. In my understanding, remaining problem in this problem is only the parameter names. My current opinion is using general parameter names like:

- `--max_file_size_for_large_files`
- `--upload_timeout_for_large_files`

and describe features which these parameters are effective in README should be fine.

@SIkebe @skullwritter What do you think?

**Comment by SIkebe** [comment]
@takezoe I am in favor of your proposal :-)

My opinion has not changed since I mentioned before.
>So two limits, one for the default and the other one for large files, would be a viable option.

**Comment by skullwritter** [comment]
but what is the minimum size for a large file?

**Comment by takezoe** [comment]
Is the minimum size limitation necessary?

**Comment by skullwritter** [comment]
the minimum size to be considered a large file, yes, because, for every person the opinion differs...

**Comment by takezoe** [comment]
I thought the max file size and timeout limitation will be applied to all file uploading at GitLFS, Issues, Pull requests, etc. There is no necessity to distinguish large files.

**Comment by skullwritter** [comment]
> I thought the max file size and timeout limitation will be applied to all file uploading at GitLFS, Issues, Pull requests, etc. There is no necessity to distinguish large files.

we already have that, now for the
``--max_file_size_for_large_files``
``--upload_timeout_for_large_files``
we don't actually have a value for a file that is considered large

**Comment by takezoe** [comment]
@skullwritter Hmm? What's your opinion? My proposal is that adding the following two options instead of per feature options (e.g. `max_file_size_issues` or `max_file_size_releases`)and they are applied to all file upload features and GitLFS.

- `--max_file_size_for_large_files`
- `--upload_timeout_for_large_files`

Does this make sense to you?

**Comment by takezoe** [comment]
Also, we need to fix `FileUploadController` because it has the max file size limitation in `MultipartConfig`:
https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/controller/FileUploadController.scala#L33

**Comment by mmestucci** [comment]
I saw the implementation about File Upload Timeout / Timeout for large files, but I still have an exception "java.util.concurrent.TimeoutException: Idle timeout expired: 3000/3000 ms" when I push a large lfs commit. It is like if this param is independent of these params. Is there other params to be configured?

**Pull request closed without merging**
