### PR TITLE
Fix style for dropdown-menu that does not display the lower part.

### PR DESCRIPTION
**Pull request by khanamura**
### Before

screenshot-192 168 75 199 2016-05-09 17-40-08

### After

screenshot-192 168 75 199 2016-05-10 18-39-36

### Before submitting a pull-request to Gitbucket I have first:

- [] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [] rebased my branch over master
- [] verified that project is compiling
- [] verified that tests are passing
- [] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [] [marked as closed](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by khanamura** [comment]
I found an adverse effect on the Wiki page.

screenshot-192 168 75 199 2016-05-10 19-58-20

**Comment by takezoe** [comment]
@khanamura Also I know that issue filter dropdown menus have same issue. I would like to consider other way.

**Comment by khanamura** [comment]
@takezoe I confirmed that issue. It seems like that problem has been resolved by this PR. 
Do you needs other way?

* on master branch

screenshot-localhost 8080 2016-05-13 14-42-04

* on this PR

screenshot-localhost 8080 2016-05-13 14-44-12

**Comment by khanamura** [comment]
@takezoe I watched another problem.
Does you say about this?

screenshot-localhost 8080 2016-05-13 17-40-37

screenshot-localhost 8080 2016-05-13 17-41-16

**Comment by takezoe** [comment]
Yes, and #1191 looks the same problem.

**Comment by takezoe** [comment]
@khanamura Fixed styles in https://github.com/gitbucket/gitbucket/commit/60099e2b0d28baa496b463d76def9f8c24a401c4. I think this is more clean way. Could you try the master branch?

**Comment by khanamura** [comment]
@takezoe I tried newest master branch and confirmed that problems have fixed. Thank you.

**Pull request closed without merging**
