### PR TITLE
Handle errors to show errors prettify and logging it.

### PR DESCRIPTION
**Pull request by kounoike**
Now, GitBucket doesn't handle exceptions. It handled by scalatra default handler. When error thrown, error description and stack trace only displayed to user. There is no log. In some case, administrator can't see it. Then, administrator can't solve problem.

In this PR, handle Exceptions by `error {}` to show errors prettify and log it by logger.

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by takezoe** [comment]
It looks nice feature because it would help debug and support. 😉 

However it's not preffered that displaying starcktrace on browser in default from the security view.
GitBucket should provide an option to switch it at least.

**Comment by kounoike** [comment]
OK, I will add such feature. and I propose one idea:
For administrator, display stack trace always even if option switch is disabled.

**Comment by kounoike** [comment]
@takezoe  OK, I commit.

for non-administrator or unauthenticated:
20170817-174631 - error - google chrome

for administrator or debug is true:
20170817-174637 - error - google chrome

each case, write error to logger:

**Comment by takezoe** [comment]
@kounoike This pull request seems to conflict with #1676 which is merged before.

**Comment by kounoike** [comment]
@takezoe OK, merged it!

**Comment by takezoe** [comment]
@kounoike Thanks for great contribution! This will decrease our support cost a lot :-)

**Comment by takezoe** [comment]
@kounoike I can't find how to configure the debug setting in the settings page. Did you forget to commit some parts of this fix?

**Comment by kounoike** [comment]
Sorry, I forgot to explain. I didn't write UI settings because it should be temporally settings by system property or environment settings. It introduced at #1617.

**Pull request merged**
