### PR TITLE
Add support auto-generated icon for default avatar.

### PR DESCRIPTION
**Pull request by kounoike**
If gravatar settings is off and user doesn't upload icon, GitBucket 4.10 returns noimage.png for avatar.
This PR changes noimage.png to auto generated icon by first letter of name and random color.

224828-manage users - google chrome

### Before submitting a pull-request to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [ ] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [ ] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by aadrian** [comment]
Please use "non-neon" (desaturated and lightened ) colors and their contrast for the text. 

E.g. Less can do this automatically 
 - http://lesscss.org/functions/#color-operations-desaturate
 - http://lesscss.org/functions/#color-operations-lighten 
 - http://lesscss.org/functions/#color-operations-contrast 

but there are other libraries too that can achieve this in an automatic way.

**Comment by kounoike** [comment]
It's not used CSS. Server-side generated PNG file.
Now, colors are generated from HSB as

```
H = randomly generated from username
bgColor = HSB(H, 1.0, 1.0)
fontColor = HSB(H + 0.5, 1.0, 0.8)
```

What values are better?

**Comment by kounoike** [comment]
@aadrian 
OK. I will commit desaturated color generation.
But, my algorithm choices Blightness = 1.0, it can't lighten more.

Because [desaturate](https://github.com/less/less.js/blob/3.x/lib/less/functions/color.js#L164) and [lighten](https://github.com/less/less.js/blob/3.x/lib/less/functions/color.js#L176) changes only saturaiton and lightness(=blightness) value, I will use hardcoded values.

**Comment by kounoike** [comment]
Current version's colors are:

103901-manage users - google chrome

(This screenshot shows full name in userlist. It's not included in this patch)

**Comment by kounoike** [comment]
Now, I use saturation and blightness same as navbar's values.
Font color is black or white. More better contrast color is selected by [contrast-ratio](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#contrast-ratiodef).

**Comment by takezoe** [comment]
Looks nicer than original screenshot!

**Comment by aadrian** [comment]
@kounoike This looks nice, thank you!

Could we also please have a different styling for Groups (Organizations)? so that it's visible right away that they're not users but orgs from the icon too? Something like a double border around icon with contrast? Or some sort of other visual hint that still keeps the nice colors.

**Comment by kounoike** [comment]
hmm... I wrote quick implementation. How about this?

224700-manage users - google chrome

or no round-cornered.
230245-manage users - google chrome

**Comment by aadrian** [comment]
@kounoike no round corners + shadow is a good visual distinction :) .

**Comment by takezoe** [comment]
Haha, Is not it excessive? Uploaded group avatar images are not transformed like this.

**Comment by kounoike** [comment]
It maybe excessive.
But images uploaded by user seems as group-like. Auto-generated avatar is not.

**Comment by takezoe** [comment]
@kounoike 

> But images uploaded by user seems as group-like. Auto-generated avatar is not.

Do you mean that users can upload an image representing that it is a group? That's right.

How about server load? I'm worrying about CPU load caused by image generation.

**Comment by kounoike** [comment]
> Do you mean that users can upload an image representing that it is a group? That's right.

Yes. Sorry for my roughly English.

> How about server load in your environment? I'm worrying about CPU load caused by image generation.

I am not too concerned. Avatars are cached by browser by previous PR.
Normally, image generation process is called only once per user.

on master branch, noname.png takes 10-20ms.
185924-manage users - google chrome

my PR, generated images take 30-90ms
185340-manage users - google chrome

user2 has uploaded image. It takes 15-52ms.

**Comment by takezoe** [comment]
@kounoike Thanks. Great work!

**Comment by kounoike** [comment]
@takezoe Additionally, I checked on my Raspberry Pi 3 (ARM 1GHz, 1GB RAM, SD-card storage).

noimage.png: 100-160ms
192527-manage users - google chrome

my PR: 300-400ms.
193209-manage users - google chrome

**Pull request merged**
