### PR TITLE
Improve GitHub compatible URL

### PR DESCRIPTION
**Pull request by int128**
This pull request allows:

1. Users can access to a repository via GitHub style URLs, e.g.
    - `git clone http://localhost:8080/hello/foo`
    - `git clone http://localhost:8080/hello/foo.git`
    - `git clone http://localhost:8080/git/hello/foo.git`
1. Users can access to a repository ended with `.git`, even if the user-agent did not contains `git` string.

Since git client initiates an operation with a request to URI `/info/refs`, it seems enough to catch and redirect for that. See [10.6 Git Internals - Transfer Protocols](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols) for details.

I've tested following commands with Git 2.10.1 (Mac), 2.11.0 (Jenkins Docker Bundled) and 2.14.1 (Windows).
- ls-remote
- clone
- fetch
- push

Of course tested with Jenkins multi-branch job.

### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

### CODE REVIEW

**Comment by ritschwumm** [comment]
iirc this was not doing this was on purpose

**Comment by ritschwumm** [comment]
iirc this was not doing this was on purpose to keep gitbucket's internal resources and repositories cleanly separated

**Comment by ritschwumm** [comment]
iirc this was not done on purpose to keep gitbucket's internal resources and repositories cleanly separated

**Comment by int128** [comment]
It might be better to implement a scalatra controller instead of the filter. I will fix.

**Comment by int128** [comment]
Here is test result with Git 2.14.1: https://gist.github.com/int128/c3c6a6d9955bd0fcc3ac0ba19da1d987

**Comment by int128** [comment]
Oops, it seems temporary failure. Would you rerun Travis job?

**Comment by takezoe** [comment]
Sure. I reran the failed java9 build.

**Pull request merged**
