### PR TITLE
Plugin hot deployment

### PR DESCRIPTION
**Pull request by takezoe**
See #1484 and #1468

### CODE REVIEW

**Comment by takezoe** [comment]
As a first step, I added "Reload plugins" button to the plugins list page in the system administration. If you put or replace plugin jars into `GITBUCKET_HOME/plugins` and push this button, plugins are loaded into GitBucket without restarting of GitBucket.

reload-plugins

Maybe it will be also possible to reload plugins automatically by watching `GITBUCKET_HOME/plugins` directory to detect modification of plugin jar files.

**Comment by McFoggy** [comment]
@takezoe it looks already fine

> put or replace plugin jars into GITBUCKET_HOME/plugins

how can you do this? the jars should be held by the java process & the classloaders and thus the operating system should prevent to overwrite/delete them? aren't they?
That's why in #1468 I proposed initially to use a temporary directory.

**Comment by takezoe** [comment]
> how can you do this?

Plugin jar files could replace or delete without any special trick in my local environment. But my current implementation isn't safe as you say, so it must be improved more. For example, old class loaders aren't closed in my current implementation, and it hasn't a way to hook plugin uninstallation.

This request is still work in progress. I will try to improve reloading process by referencing to plan which has been shown by you in #1468.

**Comment by kounoike** [comment]
@McFoggy on Windows?
Window application sometimes locks opened files. Linux/Mac application doesn't lock.

**Comment by takezoe** [comment]
Added the uninstall plugin button and fixed to load classes from the copied jar file. Remaining task are:

- Reloading is possible to be more efficient implementation
- Introduce the uninstalling plugin hook to cleanup

**Comment by takezoe** [comment]
I'm testing this branch and it looks to work fine. Could someone test as well?

**Comment by McFoggy** [comment]
@takezoe I will but probably only this week-end

**Comment by McFoggy** [comment]
@takezoe I gave it a trial on my windows machine.
My launch mode is `java -jar gitbucket.war`, here are my results

1. From empty GITBUCKET_ROOT

    - starting from an empty GITBUCKET_ROOT
    I receive the following error
    ```
    Exception in thread "Thread-11" java.nio.file.NoSuchFileException: D:\dev\platforms\gitbucket\hr\plugins
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.asIOException(WindowsException.java:106)
        at sun.nio.fs.WindowsWatchService$Poller.implRegister(WindowsWatchService.java:352)
        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
        at sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:580)
        at java.lang.Thread.run(Thread.java:745)
    ```
    - manual creation of `GITBUCKET_ROOT/plugins`
    - copy of gitbucket-gist-plugin_2.12-4.6.0.jar into `GITBUCKET_ROOT/plugins`, no automatic detection
    - login in app, click on reload plugin button
    - plugin is detected, listed and `Snippet` link appeared in header
    - click on `Snippet`, it works
    - copy of latest gitbucket-h2-backup-plugin.jar into `GITBUCKET_ROOT/plugins`, no automatic detection
    - click on reload plugin button
    - plugin is detected, listed and `H2 backup` link appeared in left menu
    - click on `H2 backup`, received the following error
    image

1. From near empty GITBUCKET_ROOT

    - starting from GITBUCKET_ROOT containing an empty plugins directory, no errors
    - copy of gitbucket-gist-plugin_2.12-4.6.0.jar into `GITBUCKET_ROOT/plugins`, automatic detection occured
    - `Snippet availables`

1. Using an initial plugin version

    - starting from GITBUCKET_ROOT containing one plugin `gitbucket-gist-plugin_2.11-4.5.0.jar`
    - app started correctly but no plugin present in app
    - gitbucket-gist-plugin_2.11-4.5.0.jar is copied into GITBUCKET_ROOT/plugins/.installed 
    - copy of gitbucket-gist-plugin_2.12-4.6.0.jar into `GITBUCKET_ROOT/plugins`, automatic detection occures but fails with the following
    ```
    Exception in thread "Thread-11" java.io.IOException: Unable to delete file: D:\dev\platforms\gitbucket\hr\plugins\.installed\gitbucket-gist-plugin_2.11-4.5.0.jar
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:207)
        at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistory.scala:176)
        at gitbucket.core.plugin.PluginWatchThread.$anonfun$run$3(PluginRegistory.scala:325)
        at gitbucket.core.plugin.PluginWatchThread.$anonfun$run$3$adapted(PluginRegistory.scala:323)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:190)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:190)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:183)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:190)
        at gitbucket.core.plugin.PluginWatchThread.run(PluginRegistory.scala:323)
   ```
    - trying to force plugin reload also fails
   ```
    java.io.IOException: Unable to delete file: D:\dev\platforms\gitbucket\hr\plugins\.installed\gitbucket-gist-plugin_2.11-4.5.0.jar
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:207)
	at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistory.scala:176)
	at gitbucket.core.controller.SystemSettingsControllerBase.$anonfun$$init$$9(SystemSettingsController.scala:188)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:279)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:189)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:175)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:278)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:277)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:33)
	at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:189)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:175)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
	at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:82)
	at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:81)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:253)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:251)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
     ...
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
    ```

**Comment by kounoike** [comment]
In #1529 I wrote, watching file system is unstable on Windows.
I think watching file system is useful for plugin development, but it's not match production usage.
It should be disabled by default, or revert it.

**Comment by kounoike** [comment]
I try to introduce `Retry` feature for `FileUtils.copyFile`. It stabilize reloading plugins on Windows.

[PluginRegistory.scala:219](https://github.com/gitbucket/gitbucket/pull/1487/files#diff-f3c729ac4faa9db0ba838b7aa0aec4d8R219), modified as:

```scala
        Retry(5, 500 millis){
          logger.info(s"Copy ${pluginJar}")
          FileUtils.copyFile(pluginJar, installedJar)
        }
```
and define `Retry` object as:

```scala
/**
  * Retry function from http://stackoverflow.com/a/40169524
  */
object Retry {
  def apply[A](times: Int, pause: Duration)(code: ⇒ A): A = {
    var result: Option[A] = None
    var remaining = times
    while (remaining > 0) {
      remaining -= 1
      try {
        result = Some(code)
        remaining = 0
      } catch {
        case _ if remaining > 0 ⇒ Thread.sleep(pause.toMillis)
      }
    }
    result.get
  }
}
```

(There are many retry implementation code and libraries found by google.)
It works as:

```
22:04:54.457 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_CREATE: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:04:54.458 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:04:54.461 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:04:54.500 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_MODIFY: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:04:54.500 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:04:54.508 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:12.105 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_MODIFY: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:12.109 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_DELETE: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:12.112 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:14.313 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_CREATE: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:14.313 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:14.315 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:14.353 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_MODIFY: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:14.353 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:14.356 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:24.086 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_MODIFY: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:24.086 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_DELETE: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:24.087 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:26.074 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_CREATE: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:26.075 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:26.077 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:26.117 [Thread-15] INFO  g.core.plugin.PluginWatchThread - ENTRY_MODIFY: gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:26.117 [Thread-15] INFO  g.core.plugin.PluginWatchThread - Reloading plugins...
22:05:26.132 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
22:05:26.634 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Copy C:\Users\kounoike\.gitbucket\plugins\gitbucket-emoji-plugin_2.12-4.4.0.jar
```

In last two lines, retry works.

**Comment by aadrian** [comment]
@kounoike very nice solution with Retry. It would be useful however to have in the logs that it's not the first time it's being tried (but on what try did really worked).

**Comment by kounoike** [comment]
@aadrian Yes, current logging code is debug purpose only.
I think the number of retried is not important. Most important incident is gave up retries.
This `Retry` implementation throws exception. It's not useful.

**Comment by takezoe** [comment]
Added retrying. If it can't get write lock to the target file, retries max 3 times.

**Comment by YoshinoriN** [comment]
@McFoggy

As you may know, your plugin `Not Found` error will be resolved if you modify the Plugin.scala's below line.

```scala
  override val controllers = Seq(
    //"/admin/h2backup" -> new H2BackupController() //befor
    "/*" -> new H2BackupController()                //after
    , "/database/backup" -> new H2BackupController()
    , "/api/v3/plugins/database/backup" -> new H2BackupController()
  )
```

I confirmed that your plugin's `Not Found` error will be resolved with the above code.

**Pull request merged**
