### PR TITLE
properly escape html metacharacters in repository description

### PR DESCRIPTION
**Pull request by ritschwumm**
try entering this description when you create a new project:
```javascript
<script>alert("hallo")</script>
```

### CODE REVIEW

**Comment by takezoe** [comment]
@ritschwumm Thanks, this is serious bug that should be fixed as soon as possible. But I think more simple fix is enough to avoid XSS like:

```scala
val escaped = HtmlFormat.escape(text)
Html(detectAndRenderLinksRegex.replaceAllIn(escaped, m => s"""<a href="${m.group(0)}">${m.group(0)}</a>"""))
```

**Comment by ritschwumm** [comment]
HtmlFormat.escape(text) returns an Html, not a String.

 i tried with StringUtil.escapeHtml instead, and
```
http://exa<mple.com
```
becomes
```
<a href="http://exa&lt;mple.com">http://exa&lt;mple.com</a>
```
then. that's wrong.

**Comment by takezoe** [comment]
@ritschwumm Right. However it's possible to remove `var` by using `foldLeft` instead of `for` expression. I will try to do it and merge after all your tests are passed.

**Comment by takezoe** [comment]
Merged.

**Pull request merged**
